---
- name: Check if exists {{ storage_mount }}
  ansible.builtin.stat:
    path: "{{ storage_mount }}"
  register: mnt_storage
- name: Ensure directory exists {{ home_data_mount }}
  ansible.builtin.file:
    path: "{{ home_data_mount }}"
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: "0755"
  when: not mnt_storage.stat.exists
- name: Mount {{ home_data_mount }}
  become: true
  ansible.posix.mount:
    path: "{{ home_data_mount }}"
    src: "{{ storage_mount }}"
    fstype: none
    opts: bind,rw
    state: mounted
  when: mnt_storage.stat.exists
- name: Create toplevel dirs
  become: true
  ansible.builtin.file:
    path: "{{ home_data_mount }}/{{ item }}"
    state: directory
    mode: "0777"
  loop: "{{ toplevel_directories }}"
- name: |
    Set toplevel directories ownership to {{ remote_user }}
  become: true
  ansible.builtin.file:
    path: "{{ home_data_mount }}/{{ item }}"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
  loop: "{{ toplevel_directories }}"
