---
apiVersion: 1
prune: true
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    orgId: 1
    version: 1
    uid: prometheus
    editable: false
  - name: Alertmanager
    type: alertmanager
    url: http://alertmanager:9093
    uid: alertmanager
    orgId: 1
    version: 1
    editable: false
    access: proxy
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true
