---
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    environment:
      - WG_DEFAULT_DNS=192.168.1.24
      - DISABLE_IPV6=true
    networks:
      wg:
        ipv4_address: 10.22.22.22
    volumes:
      - ./data:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - 50820:50820/udp
      - 50821:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
networks:
  wg:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.22.22.0/24
