---
remote_user_id: "{{ ansible_user_id }}"
storage_mount: /mnt/storage
home_data_mount: /home/{{ ansible_user_id }}/storage
toplevel_directories:
  - docker-data
stacks:
  dest: /home/{{ ansible_user_id }}/storage/docker-data/core-apps
  order: []
caddy:
  certs:
    pem:
      # yamllint disable-line rule:line-length
      location: /home/{{ ansible_user_id }}/storage/docker-data/core-apps/caddy/data/data/caddy/pki/authorities/local/root.crt
certs:
  location: /usr/local/share/ca-certificates/caddy.crt
