---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: Europe/London
      FTLCONF_webserver_api_password: ""
      FTLCONF_webserver_port: 8080,8043s
      # Fallback on router dns for local .home name resolutions
      FTLCONF_dns_upstreams: 8.8.8.8;8.8.4.4;192.168.1.1
      FTLCONF_misc_etc_dnsmasq_d: true
    volumes:
      - ./data/etc-pihole:/etc/pihole
      - ./templates/dnsmasq.d/pihole.conf.j2:/etc/dnsmasq.d/pihole.conf
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
