---
stacks:
  dest: /home/{{ ansible_user_id }}/storage/docker-data/core-apps
  common:
    dest: /home/{{ ansible_user_id }}/storage/docker-data/common
  order:
    - dir: host-exporters
    - dir: monitoring
    - dir: infisical
    - dir: search
    - dir: gitea
    - dir: docker-proxy
    - dir: url-shortener
    - dir: rss-reader
    - dir: cadvisor
