---
services:
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - ./data/valkey:/data:rw
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:2025.7.19-be392a4
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - 18088:8080
    volumes:
      - ./data/etc-searxng:/etc/searxng:rw
      - ./data/cache-searxng:/var/cache/searxng:rw
      - ./config/settings.yaml:/etc/searxng/settings.yml
    env_file:
      - ./config/searxng.env.vault
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
networks:
  searxng:
