---
version: "3.8"
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.1
    container_name: node_exporter
    command:
      - --path.rootfs=/host
    cap_add:
      - SYS_TIME
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
