---
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    environment:
      # Static IP address of the internal pihole with 53
      # port exposed
      - WG_DEFAULT_DNS=192.168.1.24
    networks:
      wg:
        ipv4_address: 10.42.42.42
      caddy: {}
    volumes:
      - ./data:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
networks:
  caddy:
    external: true
  wg:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
