---
global:
  scrape_interval: 60s
  scrape_timeout: 45s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
      scheme: http
      timeout: 10s
      api_version: v2
scrape_configs:
  # self scrape
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  # node exporters
  - job_name: node
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
      - names:
          - _nodeexporter._tcp.home
        type: SRV
        refresh_interval: 120s
