---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: Europe/London
      FTLCONF_webserver_api_password: ""
      FTLCONF_webserver_port: 8080,8043s
      # Fallback on router dns for local .home name resolutions
      FTLCONF_dns_upstreams: 8.8.8.8;8.8.4.4;192.168.1.1
      FTLCONF_misc_etc_dnsmasq_d: true
    volumes:
      - ./data/etc-pihole:/etc/pihole
      - ./templates/dnsmasq.d/pihole.conf.j2:/etc/dnsmasq.d/pihole.conf
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter:v1.0.1
    labels:
      prometheus_target: true
    environment:
      PIHOLE_HOSTNAME: pihole.home.filipmikina.com
      PORT: 9617
      PIHOLE_PROTOCOL: https
      PIHOLE_PORT: 443
      INTERVAL: 120s
    ports:
      - 19617:9617
    logging:
      driver: json-file
      options:
        max-size: 5k
        max-file: "5"
    restart: unless-stopped
    networks:
      - pihole
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
  netalertx:
    container_name: netalertx
    image: ghcr.io/jokob-sk/netalertx:25.7.4
    privileged: true
    network_mode: host
    volumes:
      - ./data/etc-pihole:/etc/pihole/:ro
      - ./data/netalertx-db:/app/db
      - ./data/netalertx-conf:/app/config
    environment:
      LOADED_PLUGINS: '["DHCPLSS","ICMP","NSLOOKUP","UI","WEBHOOK"]'
      PORT: 20211
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
networks:
  pihole:
    external: false
