---
services:
  server:
    image: docker.gitea.com/gitea:1.24
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    env_file:
      - ./config/gitea.env
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 13001:3000
      - 12222:22
  runner:
    image: gitea/act_runner:nightly
    container_name: gitea-runner
    environment:
      - GITEA_INSTANCE_URL=http://gitea:3000/
    env_file:
      - ./config/runner.env.vault
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitea
networks:
  gitea:
    external: false
